input {
   tcp {
       port => 5000
       codec => json_lines
   }
}

filter {
    if [level] == "error" {
        mutate {
            add_field => {
                "[@metadata][target_index]" => "django-logs-error-%{+yyyy.MM.dd}"
            }
        }
    } else {
        mutate {
            add_field => {
                "[@metadata][target_index]" => "django-logs-app-%{+yyyy.MM.dd}"
            }
        }
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "%{[@metadata][target_index]}"

        ilm_enabled => false
        data_stream => false
    }
}