input {
   tcp {
       port => 5000
       codec => json_lines
   }
}

filter {
    mutate {
        add_field => {
            "[@metadata][target_index]" => "django-logs-%{+yyyy.MM.dd}"
        }
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "%{[@metadata][target_index]}"

        ilm_enabled => false
        data_stream => false
    }
}