services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: crypto_analyzer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8

  web:
    build: .
    command: [
    "gunicorn",
    "crypto_analyzer_app.wsgi:application",
    "--workers",
    "2",
    "--bind",
    "0.0.0.0:8000"
    ]
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    volumes:
      - .:/app


  celery_worker:
      build: .
      command: celery -A crypto_analyzer_app worker -l info
      environment:
        DB_HOST: db
        REDIS_HOST: redis
      depends_on:
        - db
        - redis
      volumes:
        - .:/app

  celery_beat:
      build: .
      command: celery -A crypto_analyzer_app beat -l info
      environment:
        DB_HOST: db
        REDIS_HOST: redis
      depends_on:
        - db
        - redis
      volumes:
        - .:/app

  nginx:
      image: nginx:1.30
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - staticfiles:/app/staticfiles
      depends_on:
        - web

volumes:
  postgres_data:
  staticfiles: