# Generated by Django 6.0.8 on 2026-08-29 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinprice',
            name='market_cap',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='change_24h',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='analyzer.coin'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='analyzer.snapshot'),
        ),
    ]
