# Generated by Django 6.0.7 on 2026-07-26 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0002_alter_coinprice_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinprice",
            name="coin",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prices", to="analyzer.coin"),
        ),
    ]
