# Generated by Django 6.1.1 on 2026-09-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0002_coinprice_market_cap_alter_coinprice_change_24h_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinprice",
            name="change_24h",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name="coinprice",
            name="market_cap",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name="coinprice",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name="coinprice",
            name="volume_24h",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
    ]
