# Generated by Django 6.0.7 on 2026-09-03 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0004_watchlistitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="watchlistitem",
            options={"ordering": ["-added_at"], "verbose_name_plural": "list_items"},
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=12, max_digits=24)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_balance", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("user",), name="unique_user_balance")],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=12, max_digits=24)),
                ("buy_price", models.DecimalField(decimal_places=12, max_digits=36)),
                ("bought_at", models.DateTimeField(auto_now_add=True)),
                ("coin", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="target", to="analyzer.coin")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="portfolio_positions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("user", "coin"), name="unique_user_coin_portfolio")],
            },
        ),
    ]
