# Generated by Django 6.0.8 on 2026-09-11 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0004_watchlistitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="watchlistitem",
            options={"ordering": ["-added_at"], "verbose_name_plural": "list_items"},
        ),
    ]
