# Generated by Django 6.0.7 on 2026-09-15 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0005_alter_watchlistitem_options"),
        ("analyzer", "0005_alter_watchlistitem_options_balance_portfolio"),
    ]

    operations = []
