# Generated by Django 6.0.7 on 2026-09-16 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0005_alter_watchlistitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinprice",
            name="snapshot",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="coin_prices", to="analyzer.snapshot"),
        ),
    ]
