# Generated by Django 6.1.1 on 2026-09-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0006_merge_20260915_2057"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(fields=["created_at"], name="snapshot_created_at_idx"),
        ),
    ]
