# Generated by Django 6.0.7 on 2026-09-18 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0006_alter_coinprice_snapshot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="snapshot",
            options={"ordering": ["-created_at"], "verbose_name_plural": "snapshots"},
        ),
    ]
