# Generated by Django 6.1.1 on 2026-09-16 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0007_snapshot_snapshot_created_at_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="watchlistitem",
            name="analyzer_wa_user_id_b0d7b0_idx",
        ),
    ]
