# Generated by Django 6.0.7 on 2026-09-18 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0006_merge_20260915_2057"),
        ("analyzer", "0007_alter_snapshot_options"),
    ]

    operations = []
