# Generated by Django 6.0.7 on 2026-09-23 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0008_merge_20260918_2010"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="watchlistitem",
            name="analyzer_wa_user_id_b0d7b0_idx",
        ),
        migrations.AlterField(
            model_name="balance",
            name="user",
            field=models.ForeignKey(
                db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name="user_balance", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(fields=["created_at"], name="snapshot_created_at_idx"),
        ),
    ]
