# Generated by Django 6.0.7 on 2026-09-18 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0008_merge_20260918_2010"),
        ("analyzer", "0008_remove_watchlistitem_analyzer_wa_user_id_b0d7b0_idx"),
    ]

    operations = []
